# version: "3.9"
# services:
#   site:
#     build:
#       context: ./site
#       dockerfile: Dockerfile
#     env_file:
#       - ./site/.env
#     ports:
#       - 5151:80
#   api:
#     build:
#       context: ./api
#       dockerfile: Dockerfile
#     ports:
#       - 5152:3000
#     environment:
#       - DATABASE_URL=redis://db:6379
#       - PORT=3000
#       - APP_ENV=production
#   db:
#     image: redis:7.2.4-alpine
#     ports:
#       - 6379:6379

version: "3.9"
services:
  site:
    image: babelcoder/intro-to-devops-ui:1.0
    ports:
      - 5151:80
    depends_on:
      - db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5152:3000
    environment:
      - DATABASE_URL=redis://db:6379
      - PORT=3000
      - APP_ENV=production
      - DD_SERVICE=api
      - DD_ENV=prod
      - DD_VERSION=1.0
      - DD_AGENT_HOST=datadog
    labels:
      com.datadoghq.ad.check_names: '["api"]'
      com.datadoghq.ad.init_configs: "[{}]"
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port": "%%port%%"}]'
      com.datadoghq.ad.logs: '[{"source": "api", "service": "api"}]'
      com.datadoghq.tags.env: "prod"
      com.datadoghq.tags.service: "api"
      com.datadoghq.tags.version: "1.0"
    depends_on:
      - datadog
  db:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379
  kong:
    image: kong:3.3.1-alpine
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /user/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - "./kong:/user/local/kong/declarative"
  datadog:
    image: gcr.io/datadoghq/agent:7
    restart: always
    environment:
      - DD_API_KEY=431176c0b163654285e8cddfb96041d2
      - DD_SITE=ap1.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
